#!/bin/sh
. `dirname $0`/util.sh
initilize

echo =\> Creating user
useradd restrictsandbox
echo =\> Creating sudoers
cp -v data/sudoers /etc/sudoers.d/restrictsandbox
chown -v root:root /etc/sudoers.d/restrictsandbox

finalize